### ISSUE TITLE
[META] Workflow Setup for the framework

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/flow-framework#15]
### Is your feature request related to a problem?
This meta issue would solve the initial one time infrastructure setup required for the first use case: Semantic Search. 

- [x] https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/20.
- [x] https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/21.
- [x] https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/22
- [x] https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/23
