### ISSUE TITLE
[META] Onboard flow-framework to OS build

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/flow-framework#165]
### Is your feature request related to a problem?
To do the experimental release of the plugin in 2.12 OS release, plugin needs to be onboarded to the OpenSearch build system.

- [x] Create an issue on build repo to initiate the process - https://github.com/opensearch-project/opensearch-build/issues/4209
- [x] https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/168
- [x] Create the build script to generate the artifacts of the plugin. - https://github.com/opensearch-project/opensearch-ai-flow-framework/pull/166
- [x] Onboard the plugin to 2.12 manifest in build repo - https://github.com/opensearch-project/opensearch-build/pull/4229

### What solution would you like?
_A clear and concise description of what you want to happen._

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by owaiskazi19** [comment]
```
 maven:
        - maven/org/opensearch/plugin/opensearch-ai-flow-framework/maven-metadata.xml.sha512
        - maven/org/opensearch/plugin/opensearch-ai-flow-framework/maven-metadata.xml.md5
        - maven/org/opensearch/plugin/opensearch-ai-flow-framework/maven-metadata.xml.sha256
        - maven/org/opensearch/plugin/opensearch-ai-flow-framework/maven-metadata.xml.sha1
        - maven/org/opensearch/plugin/opensearch-ai-flow-framework/maven-metadata.xml
        - maven/org/opensearch/plugin/opensearch-ai-flow-framework/2.12.0.0/opensearch-ai-flow-framework-2.12.0.0-sources.jar.sha512
        - maven/org/opensearch/plugin/opensearch-ai-flow-framework/2.12.0.0/opensearch-ai-flow-framework-2.12.0.0-sources.jar.sha1
        - maven/org/opensearch/plugin/opensearch-ai-flow-framework/2.12.0.0/opensearch-ai-flow-framework-2.12.0.0.pom.sha256
        - maven/org/opensearch/plugin/opensearch-ai-flow-framework/2.12.0.0/opensearch-ai-flow-framework-2.12.0.0-sources.jar.sha256
        - maven/org/opensearch/plugin/opensearch-ai-flow-framework/2.12.0.0/opensearch-ai-flow-framework-2.12.0.0-javadoc.jar.sha256
        - maven/org/opensearch/plugin/opensearch-ai-flow-framework/2.12.0.0/opensearch-ai-flow-framework-2.12.0.0-sources.jar
        - maven/org/opensearch/plugin/opensearch-ai-flow-framework/2.12.0.0/opensearch-ai-flow-framework-2.12.0.0-javadoc.jar.sha512
        - maven/org/opensearch/plugin/opensearch-ai-flow-framework/2.12.0.0/opensearch-ai-flow-framework-2.12.0.0-javadoc.jar
        - maven/org/opensearch/plugin/opensearch-ai-flow-framework/2.12.0.0/opensearch-ai-flow-framework-2.12.0.0-sources.jar.md5
        - maven/org/opensearch/plugin/opensearch-ai-flow-framework/2.12.0.0/opensearch-ai-flow-framework-2.12.0.0.pom.sha1
        - maven/org/opensearch/plugin/opensearch-ai-flow-framework/2.12.0.0/opensearch-ai-flow-framework-2.12.0.0.pom
        - maven/org/opensearch/plugin/opensearch-ai-flow-framework/2.12.0.0/opensearch-ai-flow-framework-2.12.0.0.zip.md5
        - maven/org/opensearch/plugin/opensearch-ai-flow-framework/2.12.0.0/opensearch-ai-flow-framework-2.12.0.0-javadoc.jar.md5
        - maven/org/opensearch/plugin/opensearch-ai-flow-framework/2.12.0.0/opensearch-ai-flow-framework-2.12.0.0.zip.sha256
        - maven/org/opensearch/plugin/opensearch-ai-flow-framework/2.12.0.0/opensearch-ai-flow-framework-2.12.0.0-javadoc.jar.sha1
        - maven/org/opensearch/plugin/opensearch-ai-flow-framework/2.12.0.0/opensearch-ai-flow-framework-2.12.0.0.zip.sha512
        - maven/org/opensearch/plugin/opensearch-ai-flow-framework/2.12.0.0/opensearch-ai-flow-framework-2.12.0.0.zip.sha1
        - maven/org/opensearch/plugin/opensearch-ai-flow-framework/2.12.0.0/opensearch-ai-flow-framework-2.12.0.0.zip
        - maven/org/opensearch/plugin/opensearch-ai-flow-framework/2.12.0.0/opensearch-ai-flow-framework-2.12.0.0.pom.md5
        - maven/org/opensearch/plugin/opensearch-ai-flow-framework/2.12.0.0/opensearch-ai-flow-framework-2.12.0.0.pom.sha512
        ```
