### ISSUE TITLE
[META] Initial Repo setup

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/flow-framework#2]
Things I'll do to help set this repo up
 - [x] Baseline CODEOWNERS and MAINTAINERS
 - [x] Document DCO in CONTRIBUTING.md
 - [x] Set up 2-person PR approval
 - [x] Modify mend/renovate setup for dependency management
 - [x] Gradle wrapper
 - [x] Gradle formatting (spotless, formatter, license header)
 - [x] Build github action (including javadoc checks with checkstyle)
 - [x] Code coverage
