### ISSUE TITLE
[META] Create Infrastructure for the workflow

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/flow-framework#21]
### Is your feature request related to a problem?
Assemble plugins API with transport client for workflow setup of Semantic Search & generate a workflow id. 

- [x] https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/86
- [x] https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/83
- [x] https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/70
- [x] https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/24
- [x] Create an index and map it to the created neural pipeline created above.
- [x] Register Agent - https://github.com/opensearch-project/flow-framework/issues/194
- [x] Register Sub Agents - https://github.com/opensearch-project/flow-framework/issues/194

### What solution would you like?
Few of the task can be achieved by using MLClient from ml-commons to invoke the request on transport layer. For the others APIs of OpenSearch can be used.

### Do you have any additional context?
This will be a one time setup for creating the required complex setup for Semantic Search. Later, user would be able to invoke the SearchRequest directly using the setup created above.
