### ISSUE TITLE
[CHORE] Port Feature Branch commits to main and then 2.x

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/flow-framework#264]
Commits on feature/agent_framework that are not on main and 2.x.

 - [x] 10d08403ae2b71ea6c5bba5a8d67d3544a444116 [Feature/agent_framework] Registers a single agent with multiple tools (#198)
 - [x] ef65b3ac61351ce4bd48861d6bcd35c2af330b37 [Feature/agent_framework] Add Delete Connector Step (#211)
 - [x] 1b4d5af582cdbd7fd80f659e823591d5f52f994c [feature/agent_framework] Changing resources created format  (#231)
 - [x] 8dd6ca85b6d0b4348b2b2418e8867a1a4031f8c3 [Feature/agent_framework] Fetches modelID for RegisterAgent and Tools workflow steps (#235)
 - [x] c35a809d9cd857f2c51d9a06e5f2f7bedfe4b728 [Feature/agent_framework] Work around JceMasterKey locale bug (#239)
 - [x] 54ab4c713cfdc64a9bfcb63ac3fd0bd77084de01 Add Util method to fetch inputs from parameters, content, and previous step output (#234)
 - [x] a216e5ef89ff84395a65e1dae075105a430f14b9 [Feature/agent_framework] Add Undeploy Model Step (#236)
 - [x] 66fc68896d185b6df235e49ce713e0473b59df40 [Feature/agent_framework] Actually make the WorkflowStepFactory a Factory  (#243)
 - [x] 69b035fc4b2911d51b604edec022b251a8632c57 [Feature/agent_framework] Add Delete Model Step (#237)
 - [x] 53daf617d6851f6282f6055ec090ff7eef178bdd [Feature/agent_framework] Registers root agent with an agentId in ToolSteps (#242)
 - [x] b4e6b4427396afdd1ccddb18520312fa0ad19e07 Updating state index after register agent (#250)
 - [x] 938716738f9e1ed3ef1ab0f9baddc7ddd64104a4 [Feature/agent_framework] Added Retry functionality for Deploy Model (#245)
 - [x] 6974eafa6cbd838a25a783b83dc60ec0407002ee Only update state index on register agent (#253)
 - [x] 9b9c4067ffcbd333b7d43cccad08d7875a59c3e6 [Feature/agent_framework] Add Delete Agent Step (#246)
 - [x] 2c1401c87620d648a0f6cbabc321c932698551a1 Includ workflow id and current node id in the exception message (#262)
 - [x] bde10f5f200a87c16d19bdde006eac6fe7f8b57c Change thread queue to 100 and fix headers parsing bug (#265)
 - [x] fa96284c0a0fa6b129be2e40b66b3cfdb1cab604 Update resources_created with deploy model: (#275)
 - [x] 7bec6e8eb89cc45a1447b209e9cae2bd58dd84e5 Add setting to limit max workflow steps (#266)
 - [x] a00a715e27b9477f5f2ff90123a0690a6686cc9a [Feature/agent_framework] Add Get Workflow API to retrieve a stored template by workflow id (#273)
 - [x] affe1293bebed586ecd26de657324bc58c06ced7 [Feature/agent_framework] Adds a Search Workflow State API (#284)
 - [x] 834cb7a529ad3f9c4f41c33a3f4301934bb11e47 Permit ordering of tools in register agent step (#283)
 - [x] 614bd177c7d13ee22b49fe329d0e2f900cade999 Fix tools ordering class casting bug (#289)
 - [x] 68817bf6331042b98f2256766785a48f01c30564 Combine create api with provision api by adding a provision param (#282)
 - [x] b3060f435eba85228bfaefe23c879efd98bd5f98 [Feature/agent_framework] Deprovision API (#271)
 - [x] 6053594c6a8d30db57eaeae58a3591901ad2d0d4 [Feature/agent_framework] Adding installed plugins validation (#290)
 - [x] fe8339b922d569cc3e10aa6b1e1775716c5fee96 Add Delete Workflow API (#294)
 - [x] 1065208dafd991b949960a292c85d99c88ae5c07 Consume REST params and consistently handle error messages (#295)
 - [x] c7128a0851bc65b4dc7ab402b3d14fac5956cff1 Allow YAML Templates (#296)

This list is current as of 2023-12-15.  To update as additional PRs are merged to feature branch:
1. Pull latest upstream commits from `feature/agent_framework` branch
2. Type `git cherry 2.x -v`
3. Scroll to the bottom of the results and see where the list above ends.  Copy-paste the additional commits here
4. I'll update the PR in-progress by cherry-picking the additional commits.
