### ISSUE TITLE
[META] Resolve TODOs in code prior to release

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/flow-framework#323]
The following `TODO` comments should be resolved prior to release by one or more of:
 - doing the thing that needs to be done (if quick, write a PR, if it will take more than a day, write an issue)
 - deciding that the TODO can be handled in a future release and documenting it in an issue
 - disabling a functionality that is incomplete (and write an issue)

TODOs:
 - [x] Workflow steps that create resources but don't have a corresponding deletion should be disabled until fully implemented.  This includes register model group, create ingest pipeline, and create index. (lines 32, 36, 38) https://github.com/opensearch-project/flow-framework/issues/365
 - [x] FlowFrameworkIndicesHandler has comments on updating/concurrency/retry (lines 443, 473, 477)
 - [x] Provisioning progress detail (line 14 and WorkflowState line 54) - For later - https://github.com/opensearch-project/flow-framework/issues/385
 - [x] WorkflowState access control error line 111
 - [x] Get Workflow State get the full template?
 - [x] Provision Workflow error message improvement https://github.com/opensearch-project/flow-framework/pull/298
 - [x] Search Workflow access controller question - we need an access controller for the plugin, this can be done later.
 - [x] EncryptorUtils improve handling of which fields are encrypted
 - [x] RestHandlerUtils special handling for UI Metadata
 - [x] Create Connector Step comment on retrying
 - [x] Create Index Step and Create Ingest Pipeline Steps, same refactoring of input data already done for most other steps - these are incomplete workflow steps and not needed for the first use case.
 - [x] ProcessNode better getCause handling https://github.com/opensearch-project/flow-framework/pull/327
 - [x] ProcessNode still using generic thread pool executor https://github.com/opensearch-project/flow-framework/issues/366
 - [x] FlowFrameworkPlugin executorBuilder thread pool settings
 - [x] Template writeable comment called out on line 245 https://github.com/opensearch-project/flow-framework/issues/391

**Comment by joshpalis** [comment]
> Get Workflow State get the full template?

This doesnt seem like a priority to me, @amitgalitz wdyt?

> EncryptorUtils improve handling of which fields are encrypted

Currently the only field we need to encrypt is the `credential` field of the Create Connector Step. I think we can hold off on this item until we have a new field that requires encryption

> Template writeable comment called out on line 245

Perhaps we can just write the Template json string to the output stream and then parse the Template when reading it in. We can avoid having to write a complex writeTo method

**Comment by amitgalitz** [comment]
> > Get Workflow State get the full template?
> 
> This doesnt seem like a priority to me, @amitgalitz wdyt?
> 

Yeah don't think its a must even for GA, I also made an issue for this earlier so can probably be removed from the TODO list as its tracked there. https://github.com/opensearch-project/flow-framework/issues/171

> > EncryptorUtils improve handling of which fields are encrypted
> 
> Currently the only field we need to encrypt is the `credential` field of the Create Connector Step. I think we can hold off on this item until we have a new field that requires encryption
> 

agree on this, this is the only field that currently needs to be encrypted for us.

**Comment by dbwiddis** [comment]
> Perhaps we can just write the Template json string to the output stream and then parse the Template when reading it in.

I think we actually do this, in which case we should remove the TODO. Can you confirm?

We could get fancy and use a byte array with CBOR or SMILE 😁

**Comment by jackiehanyang** [comment]
>FlowFrameworkIndicesHandler has comments on updating/concurrency/retry (lines 443, 473, 477)

I believe we can address this in a future release, as we are not heavily relying on the update template operation currently. We can resolve this issue after thoroughly discussing the type of retry strategy we want to implement later.

**Comment by amitgalitz** [comment]
>FlowFrameworkIndicesHandler has comments on updating/concurrency/retry (lines 443, 473, 477)

Right now this is has been fixed by updating the state index correctly and adding retries. Some improvements could be made but okay to not have in GA in my opinion. I will write an issue for all these TODOs
