### ISSUE TITLE
[META] Flow Framework Development Plan / Milestones

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/flow-framework#475]
This issue will document current and future development plans for Flow Framework.   Note that features, priorities, and milestones do frequently change, so this issue will be kept updated.   We welcome community input to prioritize backlog features and participate in all phases of development.

#### 2.12.0
 - Initial design of Workflow Use Case Templates
 - Implementation of basic CRUD APIs for templates and a status API
 - Implementation of DAG-based sequencing of building blocks called Workflow Steps
 - Execution of the workflow steps via provision and deprovision API
 - Implementation of WorkflowSteps supporting the use case of a conversational assistant / query generator integrating with ML Commons Agent Framework

#### 2.13.0
 - [ ] Continue integration with front-end UI https://github.com/opensearch-project/dashboards-flow-framework
 - [ ] Implement `CreateSearchPipeline` Workflow Step integrating with Search Pipelines
   - Conceptually this will be similar to the Agent / Tool implementation
   - Implementation will start with existing Processors, and other processors in development for 2.13.0 release 
   - This will require steps corresponding to `Processor` interfaces for the Search Pipeline steps (pre-, post-, search phase)
   - This may involve development of new `Processor` types as needed.  Specifically there are some processors used in the Ingest Pipeline (including but not limited to conditional, etc.) that we want to add equivalent versions of.
   - We may add additional "basic logic" processor types for common/simple workflows that do not require full DAG complexity
   - We are exploring a processor type that can wrap an entire DAG-based workflow (#367)
 - [ ] Implement `CreateIngestPipeline` Workflow Step
   - This will involve similar `Processor` interface implementations
 - [ ] Implement search pipeline processor (existing or new) for data retrieval from OpenSearch
 - [ ] Implement search pipeline processor (existing or new) for data transformation (JSON-to-JSON)
 - [ ] Implement search pipeline processor (existing or new) for data insertion into OpenSearch
 - [ ] Integrate search pipeline processors developed in other repos

#### Backlog
 - [ ] Implement nested workflows / sub workflows to simplify templates
 - [ ] Improve provisioning / deprovisioning flexibility (fine-grained provisioning)
 - [ ] Improve customization / settings-based workflow configuration
 - [ ] Improves saved workflow grouping/tagging/searching capabilities
 - [ ] Implement steps related to OpenSearch index lifecycle
 - [ ] Implement steps for external REST APIs (similar to ML Connectors but more general/non-ML)

**Comment by minalsha** [comment]
This is a great start @dbwiddis. Lets keep incrementing on this one and add more features/functionalities as we enhance. Thanks

**Comment by dbwiddis** [comment]
>  Implement steps for external REST APIs (similar to ML Connectors but more general/non-ML)

This step in the backlog could be prioritized to support https://github.com/opensearch-project/observability/issues/1805
