### ISSUE TITLE
[META] End to end template API user experience

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/flow-framework#88]
The APIs to save and provision a workflow as part of https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/49 need to be fully integrated with existing and needed validation checks and exception handling.  The goal is to provide fast-failure validation information to a user giving them enough information to correct an invalid template, and also provide appropriate feedback to a user when a workflow fails, identifying enough detail to correct the issue.

The following steps need to be completed:

### P0 Tasks
 - [x] Update existing workflow parsing code to replace `IllegalArgumentException` with a [`FlowFrameworkException`](https://github.com/opensearch-project/opensearch-ai-flow-framework/blob/main/src/main/java/org/opensearch/flowframework/exception/FlowFrameworkException.java) including an appropriate `RestStatus`.
 - [x] Update existing workflow process execution code to handle the cause of exceptionally completed futures (`TimeoutException` or other failures) with a [`FlowFrameworkException`](https://github.com/opensearch-project/opensearch-ai-flow-framework/blob/main/src/main/java/org/opensearch/flowframework/exception/FlowFrameworkException.java) including an appropriate `RestStatus`.
 - [x] Update the `RestResponse` for the API method(s) to handle these exceptions, and build a response to the user containing an appropriately detailed error message.
 - [x] Add input/output data validation checks to the workflow parsing.  https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/18 and https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/67. These may involve updating the workflow step factory.
 - [x] #105
 - [x] https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/108
 - [x] https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/123
 - [x] https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/131
 - [x] https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/149
 - [x] Handle optional params for Register Model, Deploy Model and Create Connector similar to done in Model Group Step
 - [x] https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/22
 - [x] https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/158
 - [x] https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/75
 - [x] Combine RegisterLocalModelStep and GetMLTaskStep (Covered by PR #220)
 - [x] https://github.com/opensearch-project/flow-framework/issues/210
 - [x] Integrate tests of the above features with Integration Testing. Refactor tests as necessary to either mock or make use of the OpenSearch test framework's clients
 - [x] https://github.com/opensearch-project/flow-framework/issues/170
 - [x] https://github.com/opensearch-project/flow-framework/issues/279
 - [x] https://github.com/opensearch-project/flow-framework/pull/290

### P1 Tasks
- [x] #99 
- [ ] #103 
- [ ] #104

**Comment by joshpalis** [comment]
> Refactor parsing steps as necessary to generate failures as early as possible in the process. Consider adding a "dryrun" parameter to the template saving APIs for the user to perform validation without making any changes.

This is a good idea, perhaps we can run the template through the workflow process sorter to validate the graph and not execute it

**Comment by dbwiddis** [comment]
> Perhaps we can run the template through the workflow process sorter to validate the graph and not execute it

Yep, there's a private method we can probably make public to more easily enable that.

**Comment by owaiskazi19** [comment]
Regarding the 4th point, trying to understand more for validation. Should we have a dry run param or validation should be done every time there's a call to template API? Be it to just to save the template or start the provisioning.

**Comment by joshpalis** [comment]
> Regarding the 4th point, trying to understand more for validation. Should we have a dry run param or validation should be done every time there's a call to template API? Be it to just to save the template or start the provisioning.|

If we add validation by default as a prerequisite to saving a WIP template, that could be a frustrating experience for a builder. In that regard, I think it should be a separate capability and having an optional dry-run param for the `RestCreateWorkflowAction` to validate prior to saving makes sense. 

Having the dry-run param for the `RestProvisionWorkflowAction` wouldn't make sense here, since validation is done when we topologically sort the workflow.

**Comment by dbwiddis** [comment]
> If we add validation by default as a prerequisite to saving a WIP template, that could be a frustrating experience for a builder. In that regard, I think it should be a separate capability and having an optional dry-run param for the `RestCreateWorkflowAction` to validate prior to saving makes sense.

I think validation goes more with the "execution" portion, but we should be able to do the validation before saving.  Which means we sort of need a "save-and-execute" single API call.

Which brings back up the possibility of combining APIs.

We have
```
POST _plugins/_flow_framework/workflow
{
    // use case template
}
```
followed by
```
POST _plugins/_flow_framework/workflow/<workflow_id>/_provision
{}
```
This works well for a "save WIP and finally execute when done" but in the case we have a completed/debugged template that we always want to execute, we could do that all-in-one with:
```
POST _plugins/_flow_framework/workflow/_provision
{
    // use case template
}
```
Now, throw a validation param in there and we have a one-liner just like we want:
```
POST _plugins/_flow_framework/workflow/_provision?dryrun=true
{
    // use case template
}
```
(or similar)

**Comment by joshpalis** [comment]
Closing as completed since the remaining P1 items have separate issues tracking them
