### ISSUE TITLE
[META] Implement basic manual Undo/Rollback capability

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/flow-framework#89]
https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/32 describes an overall vision for a full rollback or overwrite capability, and near the bottom says:
> ### What will it take to execute?
> 
> In the near term we should keep track of resources created in order to enable manual removal, regardless of any more automatic behavior.

Which means steps 1 and 3 of:

> We need a capability to:
> 
> 1. Track what resources have been created in a workflow execution
> 2. Automate the removal of these resources (if possible)
> 3. Provide users with a specific list of resources created to enable manual removal in case automated removal fails, or they want more control over the process.

This issue is intended to do exactly that near term requirement.  Review comments on #32 for some more context.

 - [x] Store all resources created in a state index.  https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/74
 - [x] Update Template execution APIs to ensure that this list of resources created is returned to the user as part of the successful response.
 - [x] Update Template execution APIs to ensure that this list of resources created is returned to the user as part of a failed response.
 - [x] Provide a REST API that allows a user to list the resources they created.  This will probably use the same code path which was used in the response generation in the previous steps.
 - [ ] Provide a REST API that allows a user to delete the resources they created.  Look into tagging the resources in such a way that they can be easily filtered/identified.  Consider integrating this as an optional parameter to the delete template API.
